[versions]
android-activity = "1.10.1"
android-core = "1.15.0"
android-datastore = "1.2.1"
android-gradle-plugin = "9.1.0"
android-media3 = "1.10.1"
android-work = "2.10.0"
coil = "3.6.0"
compose = "1.12.0"
compose-material = "1.7.3"
compose-material3 = "1.12.0-alpha03"
cyclonedx = "3.4.1"
detekt = "2.0.0-alpha.6"
jna = "5.14.0"
kotlin = "2.4.10"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.0"
ktor = "3.0.1"
ktlint-cli = "1.8.0"
ktlint-gradle = "14.2.0"
vlcj = "4.8.3"

[libraries]
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity" }
android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android-core" }
android-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "android-datastore" }
android-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "android-media3" }
android-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "android-media3" }
android-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "android-media3" }
android-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "android-work" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
jna-core = { module = "net.java.dev.jna:jna-jpms", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform-jpms", version.ref = "jna" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }

[bundles]
android-media3 = ["android-media3-exoplayer", "android-media3-exoplayer-hls", "android-media3-ui"]
coil-common = ["coil-compose", "coil-network-ktor", "coil-svg"]
compose-common = ["compose-runtime", "compose-foundation", "compose-material3", "compose-material-icons"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
