import org.gradle.api.tasks.Sync
import java.io.StringReader
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.util.Properties

plugins {
    kotlin("multiplatform")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
}

val generatedAppResources = layout.buildDirectory.dir("generated/wukkiAppResources")
val generatedBuildInfo = layout.buildDirectory.dir("generated/wukkiBuildInfo/desktopMain/kotlin")
val vlcRuntimePath = providers.environmentVariable("WUKKI_VLC_RUNTIME")
val wukkiVersion = providers.gradleProperty("wukkiVersion")
    .orElse(providers.environmentVariable("GITHUB_REF_NAME").map { it.removePrefix("v") })
    .orElse("1.0.0")
val wukkiBuild = providers.gradleProperty("wukkiBuild")
    .orElse(providers.environmentVariable("GITHUB_SHA").map { it.take(7) })
    .orElse("local")

val generateBuildInfo by tasks.registering {
    group = "build"
    description = "Generates the application version and build identifier used by the About screen."
    val outputDirectory = generatedBuildInfo
    inputs.property("version", wukkiVersion)
    inputs.property("build", wukkiBuild)
    outputs.dir(outputDirectory)
    doLast {
        val escapeKotlin = { value: String -> value.replace("\\", "\\\\").replace("\"", "\\\"") }
        val output = outputDirectory.get().file("hu/wukki/tv/WukkiBuildInfo.kt").asFile
        output.parentFile.mkdirs()
        output.writeText(
            """package hu.wukki.tv

/** Generated by Gradle; do not edit manually. */
object WukkiBuildInfo {
    const val VERSION = "${escapeKotlin(wukkiVersion.get())}"
    const val BUILD = "${escapeKotlin(wukkiBuild.get())}"
}
"""
        )
    }
}
val prepareVlcRuntime by tasks.registering(Sync::class) {
    group = "distribution"
    description = "Places an externally supplied VLC runtime and third-party notices into the app resources."
    from(rootProject.layout.projectDirectory.dir("LICENSES")) {
        into("common/licenses")
    }
    inputs.property("vlcRuntimePath", vlcRuntimePath.orElse(""))
    vlcRuntimePath.orNull?.let { runtimePath ->
        from(file(runtimePath)) { into("common/runtime/vlc") }
    }
    into(generatedAppResources)
}

kotlin {
    jvm("desktop")

    sourceSets {
        val desktopMain by getting {
            kotlin.srcDir(generatedBuildInfo)
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0")
                implementation("io.coil-kt.coil3:coil-compose:3.0.4")
                implementation("io.coil-kt.coil3:coil-network-ktor3:3.0.4")
                implementation("io.coil-kt.coil3:coil-svg:3.0.4")
                // Coil's Ktor integration needs a JVM HTTP engine for remote tvg-logo URLs.
                implementation("io.ktor:ktor-client-java:3.0.1")
                implementation("uk.co.caprica:vlcj:4.8.3")
            }
        }
        val desktopTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "hu.wukki.tv.MainKt"
        nativeDistributions {
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb
            )
            packageName = "Wukki TV"
            packageVersion = wukkiVersion.get()
            macOS { iconFile.set(rootProject.file("packaging/icons/wukki-tv.icns")) }
            windows { iconFile.set(rootProject.file("packaging/icons/wukki-tv.ico")) }
            linux { iconFile.set(rootProject.file("packaging/icons/wukki-tv.png")) }
            appResourcesRootDir.set(generatedAppResources)
        }
    }
}

tasks.matching { it.name == "prepareAppResources" || it.name.startsWith("package") }.configureEach {
    dependsOn(prepareVlcRuntime)
}

tasks.matching { it.name == "compileKotlinDesktop" }.configureEach {
    dependsOn(generateBuildInfo)
}

val checkLocalizationBundles by tasks.registering {
    group = "verification"
    description = "Checks UTF-8 encoding and matching keys in the Hungarian and English localization bundles."
    doLast {
        fun loadBundle(name: String): Set<String> {
            val path = file("src/desktopMain/resources/i18n/messages_$name.properties").toPath()
            val content = StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(ByteBuffer.wrap(Files.readAllBytes(path)))
                .toString()
            check(!content.startsWith('\uFEFF')) { "$path must be UTF-8 without a BOM." }
            check('\r' !in content) { "$path must use Unix (LF) line endings." }
            return Properties().apply { load(StringReader(content)) }.stringPropertyNames()
        }

        val hungarian = loadBundle("hu")
        val english = loadBundle("en")
        check(hungarian == english) {
            "Localization keys differ. Missing from English: ${hungarian - english}; missing from Hungarian: ${english - hungarian}"
        }
    }
}

tasks.matching { it.name == "check" }.configureEach {
    dependsOn(checkLocalizationBundles)
}
