import org.gradle.api.tasks.Sync
import java.io.StringReader
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.util.Properties

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.android.kotlin.multiplatform.library")
}

val generatedAppResources = layout.buildDirectory.dir("generated/wukkiAppResources")
val generatedBuildInfo = layout.buildDirectory.dir("generated/wukkiBuildInfo/desktopMain/kotlin")
val generatedAndroidSharedKotlin = layout.buildDirectory.dir("generated/wukkiAndroidShared/kotlin")
val vlcRuntimePath = providers.environmentVariable("WUKKI_VLC_RUNTIME")
val wukkiVersion = providers.gradleProperty("wukkiVersion")
    .orElse(providers.environmentVariable("GITHUB_REF_NAME").map { it.removePrefix("v") })
    .orElse("1.0.0")
val wukkiBuild = providers.gradleProperty("wukkiBuild")
    .orElse(providers.environmentVariable("GITHUB_SHA").map { it.take(7) })
    .orElse("local")

val generateBuildInfo by tasks.registering {
    group = "build"
    description = "Generates the application version and build identifier used by the About screen."
    val outputDirectory = generatedBuildInfo
    inputs.property("version", wukkiVersion)
    inputs.property("build", wukkiBuild)
    outputs.dir(outputDirectory)
    doLast {
        val escapeKotlin = { value: String -> value.replace("\\", "\\\\").replace("\"", "\\\"") }
        val output = outputDirectory.get().file("hu/wukki/tv/WukkiBuildInfo.kt").asFile
        output.parentFile.mkdirs()
        output.writeText(
            """package hu.wukki.tv

/** Generated by Gradle; do not edit manually. */
object WukkiBuildInfo {
    const val VERSION = "${escapeKotlin(wukkiVersion.get())}"
    const val BUILD = "${escapeKotlin(wukkiBuild.get())}"
}
"""
        )
    }
}
val prepareVlcRuntime by tasks.registering(Sync::class) {
    group = "distribution"
    description = "Places an externally supplied VLC runtime and third-party notices into the app resources."
    from(rootProject.layout.projectDirectory.dir("LICENSES")) {
        into("common/licenses")
    }
    inputs.property("vlcRuntimePath", vlcRuntimePath.orElse(""))
    vlcRuntimePath.orNull?.let { runtimePath ->
        from(file(runtimePath)) {
            // Gradle/jpackage changes copied file timestamps, which invalidates VLC's binary
            // plugin cache. libVLC scans the bundled plugins at startup instead.
            exclude("plugins/plugins.dat")
            into("common/runtime/vlc")
        }
    }
    into(generatedAppResources)
}

/**
 * The desktop target predates the Android target and still owns the shared UI and domain source
 * tree. Copy the platform-neutral subset for Android instead of compiling the desktop source
 * directory directly: Kotlin source-set excludes are not reliably applied to an added directory.
 */
val prepareAndroidSharedSources by tasks.registering(Sync::class) {
    from("src/desktopMain/kotlin") {
        exclude(
            "hu/wukki/tv/Main.kt",
            "hu/wukki/tv/data/LocalStore.kt",
            "hu/wukki/tv/data/DeviceInfoProvider.kt",
            "hu/wukki/tv/player/AspectRatioImagePainter.kt",
            "hu/wukki/tv/player/OverlayTheme.kt",
            "hu/wukki/tv/player/PlaybackController.kt",
            "hu/wukki/tv/player/VlcRuntimeResolver.kt",
            "hu/wukki/tv/ScreenWakeController.kt",
            "hu/wukki/tv/ui/app/DesktopWukkiApp.kt"
        )
    }
    into(generatedAndroidSharedKotlin)
}

/**
 * VLC.app's executable supplies its own @rpath entries. libVLC is instead loaded by the JVM in
 * the packaged Wukki app, so those entries are not available to decoder plugins. Give the copied
 * libraries a loader-relative search path before Compose bundles and signs the app. Plugins are
 * deliberately left untouched because VLC validates their timestamps through plugins.dat.
 */
val patchMacVlcRuntime by tasks.registering {
    group = "distribution"
    description = "Adds loader-relative VLC library paths to the packaged macOS runtime."
    dependsOn(prepareVlcRuntime)
    onlyIf {
        System.getProperty("os.name").startsWith("Mac", ignoreCase = true) && vlcRuntimePath.isPresent
    }
    inputs.dir(generatedAppResources)
    doLast {
        val runtime = generatedAppResources.get().dir("common/runtime/vlc").asFile

        fun runCommand(vararg arguments: String): String {
            val process = ProcessBuilder(*arguments)
                .redirectErrorStream(true)
                .start()
            val output = process.inputStream.bufferedReader().use { it.readText() }
            check(process.waitFor() == 0) { "Command failed: ${arguments.joinToString(" ")}\\n$output" }
            return output
        }

        fun addRpath(binary: File, rpath: String) {
            if (runCommand("otool", "-l", binary.absolutePath).contains("path $rpath (")) return
            runCommand("install_name_tool", "-add_rpath", rpath, binary.absolutePath)
        }

        runtime.resolve("lib").listFiles { file -> file.extension == "dylib" }
            ?.forEach { addRpath(it, "@loader_path") }
    }
}

kotlin {
    jvm("desktop")
    androidLibrary {
        namespace = "hu.wukki.tv.shared"
        compileSdk = 36
        minSdk = 26
        androidResources { enable = true }
    }

    sourceSets {
        val androidMain by getting {
            // The Compose features, models and IPTV logic are shared source. Platform entry
            // points, local stores and video renderers are supplied from androidMain instead.
            kotlin.srcDir(generatedAndroidSharedKotlin)
            resources.srcDir("src/desktopMain/resources")
            kotlin.srcDir(generatedBuildInfo)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")
                implementation("io.coil-kt.coil3:coil-compose:3.0.4")
                implementation("io.coil-kt.coil3:coil-network-ktor3:3.0.4")
                implementation("io.coil-kt.coil3:coil-svg:3.0.4")
                implementation("io.ktor:ktor-client-okhttp:3.0.1")
                implementation("androidx.datastore:datastore-preferences:1.2.1")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0")
                implementation("androidx.work:work-runtime-ktx:2.10.0")
                implementation("androidx.media3:media3-exoplayer:1.10.1")
                implementation("androidx.media3:media3-exoplayer-hls:1.10.1")
                implementation("androidx.media3:media3-ui:1.10.1")
            }
        }
        val desktopMain by getting {
            kotlin.srcDir(generatedBuildInfo)
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0")
                implementation("io.coil-kt.coil3:coil-compose:3.0.4")
                implementation("io.coil-kt.coil3:coil-network-ktor3:3.0.4")
                implementation("io.coil-kt.coil3:coil-svg:3.0.4")
                // Coil's Ktor integration needs a JVM HTTP engine for remote tvg-logo URLs.
                implementation("io.ktor:ktor-client-java:3.0.1")
                implementation("uk.co.caprica:vlcj:4.8.3")
                implementation("net.java.dev.jna:jna-jpms:5.14.0")
                implementation("net.java.dev.jna:jna-platform-jpms:5.14.0")
            }
        }
        val desktopTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0")
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "hu.wukki.tv.MainKt"
        nativeDistributions {
            // vlcj's direct-render callback allocates video buffers through sun.misc.Unsafe.
            // This module is not part of Compose Desktop's default jlink image.
            modules("jdk.unsupported")
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Dmg,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb
            )
            packageName = "Wukki TV"
            packageVersion = wukkiVersion.get()
            macOS { iconFile.set(rootProject.file("packaging/icons/wukki-tv.icns")) }
            windows { iconFile.set(rootProject.file("packaging/icons/wukki-tv.ico")) }
            linux { iconFile.set(rootProject.file("packaging/icons/wukki-tv.png")) }
            appResourcesRootDir.set(generatedAppResources)
        }
    }
}

tasks.matching { it.name == "prepareAppResources" }.configureEach {
    dependsOn(patchMacVlcRuntime)
}

tasks.matching { it.name.startsWith("package") }.configureEach {
    dependsOn(patchMacVlcRuntime)
}

tasks.matching { it.name == "compileKotlinDesktop" }.configureEach {
    dependsOn(generateBuildInfo)
}

tasks.matching { it.name == "compileAndroidMain" }.configureEach {
    dependsOn(generateBuildInfo, prepareAndroidSharedSources)
}

val checkLocalizationBundles by tasks.registering {
    group = "verification"
    description = "Checks UTF-8 encoding and matching keys in the Hungarian and English localization bundles."
    doLast {
        fun loadBundle(name: String): Set<String> {
            val path = file("src/desktopMain/resources/i18n/messages_$name.properties").toPath()
            val content = StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(ByteBuffer.wrap(Files.readAllBytes(path)))
                .toString()
            check(!content.startsWith('\uFEFF')) { "$path must be UTF-8 without a BOM." }
            check('\r' !in content) { "$path must use Unix (LF) line endings." }
            return Properties().apply { load(StringReader(content)) }.stringPropertyNames()
        }

        val hungarian = loadBundle("hu")
        val english = loadBundle("en")
        check(hungarian == english) {
            "Localization keys differ. Missing from English: ${hungarian - english}; missing from Hungarian: ${english - hungarian}"
        }
    }
}

tasks.matching { it.name == "check" }.configureEach {
    dependsOn(checkLocalizationBundles)
}
