import java.io.StringReader
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.android.kmp.library)
    id("wukki.quality")
    id("wukki.dependency-locking")
}

val generatedBuildInfo = layout.buildDirectory.dir("generated/wukkiBuildInfo/commonMain/kotlin")
val wukkiVersion = rootProject.extra["wukkiDisplayVersion"].toString()
val wukkiBuild = rootProject.extra["wukkiBuildId"].toString()

val generateBuildInfo by tasks.registering {
    group = "build"
    description = "Generates the application version and build identifier used by the About screen."
    inputs.property("version", wukkiVersion)
    inputs.property("build", wukkiBuild)
    outputs.dir(generatedBuildInfo)
    doLast {
        val escape = { value: String -> value.replace("\\", "\\\\").replace("\"", "\\\"") }
        val output = generatedBuildInfo.get().file("hu/wukki/tv/WukkiBuildInfo.kt").asFile
        output.parentFile.mkdirs()
        output.writeText(
            """package hu.wukki.tv

/** Generated by Gradle; do not edit manually. */
object WukkiBuildInfo {
    const val VERSION = "${escape(wukkiVersion)}"
    const val BUILD = "${escape(wukkiBuild)}"
}
""",
        )
    }
}

kotlin {
    // Keep compilation and the desktop runtime on the supported Java 21 toolchain.
    jvmToolchain(21)
    compilerOptions {
        // `expect`/`actual` platform classes are intentional in this KMP module.
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    jvm("desktop")
    android {
        namespace = "hu.wukki.tv.shared"
        compileSdk = 37
        minSdk = 26
        androidResources { enable = true }
        withHostTest {}
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDir(generatedBuildInfo)
            dependencies {
                implementation(libs.bundles.compose.common)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.bundles.coil.common)
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }
        val androidMain by getting {
            kotlin.srcDir("src/jvmCommon/kotlin")
        }
        val desktopMain by getting {
            kotlin.srcDir("src/jvmCommon/kotlin")
        }
        val androidHostTest by getting {
            kotlin.srcDir("src/jvmCommonTest/kotlin")
        }
        val desktopTest by getting {
            kotlin.srcDir("src/jvmCommonTest/kotlin")
        }
    }
}

tasks.matching { it.name == "compileKotlinDesktop" || it.name == "compileAndroidMain" }.configureEach {
    dependsOn(generateBuildInfo)
}

tasks.matching { it.name.startsWith("runKtlint") }.configureEach {
    dependsOn(generateBuildInfo)
}

val checkLocalizationBundles by tasks.registering {
    group = "verification"
    description = "Checks UTF-8 encoding and matching keys in the Hungarian and English localization bundles."
    doLast {
        fun loadBundle(name: String): Set<String> {
            val path = file("src/commonMain/resources/i18n/messages_$name.properties").toPath()
            val content =
                StandardCharsets.UTF_8
                    .newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(Files.readAllBytes(path)))
                    .toString()
            check(!content.startsWith('\uFEFF')) { "$path must be UTF-8 without a BOM." }
            check('\r' !in content) { "$path must use Unix (LF) line endings." }
            return Properties().apply { load(StringReader(content)) }.stringPropertyNames()
        }
        val hungarian = loadBundle("hu")
        val english = loadBundle("en")
        check(hungarian == english) {
            "Localization keys differ. Missing from English: ${hungarian - english}; missing from Hungarian: ${english - hungarian}"
        }
    }
}

tasks.matching { it.name == "check" }.configureEach { dependsOn(checkLocalizationBundles) }
