import java.io.StringReader
import java.nio.ByteBuffer
import java.nio.charset.CodingErrorAction
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.util.Properties

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.android.kotlin.multiplatform.library")
}

val generatedBuildInfo = layout.buildDirectory.dir("generated/wukkiBuildInfo/commonMain/kotlin")
val wukkiVersion = providers.gradleProperty("wukkiVersion")
    .orElse(providers.environmentVariable("GITHUB_REF_NAME").map { it.removePrefix("v") })
    .orElse("1.0.0")
val wukkiBuild = providers.gradleProperty("wukkiBuild")
    .orElse(providers.environmentVariable("GITHUB_SHA").map { it.take(7) })
    .orElse("local")

val generateBuildInfo by tasks.registering {
    group = "build"
    description = "Generates the application version and build identifier used by the About screen."
    inputs.property("version", wukkiVersion)
    inputs.property("build", wukkiBuild)
    outputs.dir(generatedBuildInfo)
    doLast {
        val escape = { value: String -> value.replace("\\", "\\\\").replace("\"", "\\\"") }
        val output = generatedBuildInfo.get().file("hu/wukki/tv/WukkiBuildInfo.kt").asFile
        output.parentFile.mkdirs()
        output.writeText(
            """package hu.wukki.tv

/** Generated by Gradle; do not edit manually. */
object WukkiBuildInfo {
    const val VERSION = "${escape(wukkiVersion.get())}"
    const val BUILD = "${escape(wukkiBuild.get())}"
}
"""
        )
    }
}

kotlin {
    jvm("desktop")
    androidLibrary {
        namespace = "hu.wukki.tv.shared"
        compileSdk = 36
        minSdk = 26
        androidResources { enable = true }
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDir(generatedBuildInfo)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0")
                implementation("io.coil-kt.coil3:coil-compose:3.0.4")
                implementation("io.coil-kt.coil3:coil-network-ktor3:3.0.4")
                implementation("io.coil-kt.coil3:coil-svg:3.0.4")
            }
        }
        val commonTest by getting {
            dependencies { implementation(kotlin("test")) }
        }
        val androidMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")
                implementation("io.ktor:ktor-client-okhttp:3.0.1")
                implementation("androidx.datastore:datastore-preferences:1.2.1")
                implementation("androidx.work:work-runtime-ktx:2.10.0")
                implementation("androidx.media3:media3-exoplayer:1.10.1")
                implementation("androidx.media3:media3-exoplayer-hls:1.10.1")
                implementation("androidx.media3:media3-ui:1.10.1")
            }
        }
        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0")
                implementation("io.ktor:ktor-client-java:3.0.1")
                implementation("uk.co.caprica:vlcj:4.8.3")
                implementation("net.java.dev.jna:jna-jpms:5.14.0")
                implementation("net.java.dev.jna:jna-platform-jpms:5.14.0")
            }
        }
        val desktopTest by getting {
            dependencies { implementation(kotlin("test")) }
        }
    }
}

tasks.matching { it.name == "compileKotlinDesktop" || it.name == "compileAndroidMain" }.configureEach {
    dependsOn(generateBuildInfo)
}

val checkLocalizationBundles by tasks.registering {
    group = "verification"
    description = "Checks UTF-8 encoding and matching keys in the Hungarian and English localization bundles."
    doLast {
        fun loadBundle(name: String): Set<String> {
            val path = file("src/commonMain/resources/i18n/messages_$name.properties").toPath()
            val content = StandardCharsets.UTF_8.newDecoder()
                .onMalformedInput(CodingErrorAction.REPORT)
                .onUnmappableCharacter(CodingErrorAction.REPORT)
                .decode(ByteBuffer.wrap(Files.readAllBytes(path)))
                .toString()
            check(!content.startsWith('\uFEFF')) { "$path must be UTF-8 without a BOM." }
            check('\r' !in content) { "$path must use Unix (LF) line endings." }
            return Properties().apply { load(StringReader(content)) }.stringPropertyNames()
        }
        val hungarian = loadBundle("hu")
        val english = loadBundle("en")
        check(hungarian == english) {
            "Localization keys differ. Missing from English: ${hungarian - english}; missing from Hungarian: ${english - hungarian}"
        }
    }
}

tasks.matching { it.name == "check" }.configureEach { dependsOn(checkLocalizationBundles) }
